# GTK3 theme generation (for adw-gtk3-dark)
# Receives: $base00-$base0F, $THEME_NAME

GTK3_DIR="$HOME/.config/gtk-3.0"

mkdir -p "$GTK3_DIR"

# Generate GTK3 CSS with base16 colors (comprehensive version matching gtk4.sh)
cat > "$GTK3_DIR/gtk.css" << EOF
/**
 * Base16 Theme: $THEME_NAME
 * Generated by theme-set for adw-gtk3
 */

/* Base16 color palette */
@define-color background $base00;
@define-color foreground $base05;

@define-color black $base00;
@define-color red $base08;
@define-color green $base0B;
@define-color yellow $base0A;
@define-color blue $base0D;
@define-color magenta $base0E;
@define-color cyan $base0C;
@define-color white $base05;
@define-color bright_black $base03;
@define-color bright_red $base08;
@define-color bright_green $base0B;
@define-color bright_yellow $base0A;
@define-color bright_blue $base0D;
@define-color bright_magenta $base0E;
@define-color bright_cyan $base0C;
@define-color bright_white $base07;

/* Adwaita/libadwaita color overrides */
@define-color accent_bg_color @blue;
@define-color accent_fg_color @background;
@define-color accent_color @blue;

@define-color window_bg_color @background;
@define-color window_fg_color @foreground;

@define-color view_bg_color @black;
@define-color view_fg_color @foreground;
@define-color sidebar_bg_color $base01;
@define-color sidebar_fg_color @foreground;
@define-color sidebar_backdrop_color $base01;
@define-color sidebar_shade_color @black;

@define-color headerbar_bg_color alpha(@foreground, 0.1);
@define-color headerbar_fg_color @foreground;
@define-color headerbar_backdrop_color @black;
@define-color headerbar_shade_color @black;
@define-color card_bg_color alpha(@foreground, 0.1);
@define-color card_fg_color @foreground;

@define-color popover_bg_color $base01;
@define-color popover_fg_color @foreground;

@define-color destructive_bg_color @red;
@define-color destructive_fg_color @background;

@define-color success_bg_color @green;
@define-color success_fg_color @background;

@define-color warning_bg_color @yellow;
@define-color warning_fg_color @background;

@define-color error_bg_color @red;
@define-color error_fg_color @background;

@define-color dialog_bg_color @background;
@define-color dialog_fg_color @foreground;

@define-color borders alpha(@foreground, 0.1);

/* GTK3 legacy color variables */
@define-color theme_fg_color @foreground;
@define-color theme_text_color @foreground;
@define-color theme_bg_color @background;
@define-color theme_base_color @black;
@define-color theme_selected_bg_color @blue;
@define-color theme_selected_fg_color @background;
@define-color insensitive_bg_color @background;
@define-color insensitive_fg_color @bright_black;
@define-color insensitive_base_color @black;
@define-color theme_unfocused_fg_color @foreground;
@define-color theme_unfocused_text_color @foreground;
@define-color theme_unfocused_bg_color @background;
@define-color theme_unfocused_base_color @black;
@define-color theme_unfocused_selected_bg_color @blue;
@define-color theme_unfocused_selected_fg_color @background;
@define-color unfocused_insensitive_color @bright_black;
@define-color unfocused_borders alpha(@foreground, 0.1);
@define-color warning_color @yellow;
@define-color error_color @red;
@define-color success_color @green;
@define-color destructive_color @red;

/* Content view colors */
@define-color content_view_bg @black;
@define-color text_view_bg @black;

/* Dialog styling */
messagedialog {
    background-color: @dialog_bg_color;
}

messagedialog label {
    color: @dialog_fg_color;
}

messagedialog button {
    background-color: $base01;
    color: @foreground;
    border: 1px solid @bright_black;
}

messagedialog button:hover {
    background-color: @blue;
}

/* Alert dialog styling */
alertdialog.background {
    background-color: @dialog_bg_color;
    color: @dialog_fg_color;
}

alertdialog .titlebar {
    background-color: @headerbar_bg_color;
    color: @headerbar_fg_color;
}

alertdialog box {
    background-color: @dialog_bg_color;
}

alertdialog label {
    color: @dialog_fg_color;
}

/* File chooser */
filechooser .dialog-action-box {
    border-top: 1px solid @bright_black;
}

filechooser #pathbarbox {
    border-bottom: 1px solid @bright_black;
}

/* Toast notifications */
toast {
    background-color: $base01;
    color: @foreground;
}

toast button.circular.flat.image-button:hover {
    color: @background;
    background-color: @red;
}

/* Banner */
banner revealer widget {
    background: @bright_black;
    padding: 5px;
    color: @foreground;
}
EOF
