#!/usr/bin/env python3
"""Hyprland border/decoration colors. Receives $base00-$base0F, $CACHE_DIR, $THEME_NAME."""

import os
import shutil
import subprocess

CACHE_DIR = os.environ["CACHE_DIR"]
THEME_NAME = os.environ.get("THEME_NAME", "unknown")


def luminance(hex_color):
    h = hex_color.lstrip("#")
    channels = (int(h[i : i + 2], 16) / 255 for i in (0, 2, 4))
    linear = [
        c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4 for c in channels
    ]
    return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2]


def argb(hex_color, alpha):
    return f"0x{alpha}{hex_color.lstrip('#')}"


active, inactive = os.environ["base0D"], os.environ["base03"]

if luminance(inactive) > luminance(active):
    active, inactive = inactive, active

out = f"""-- {THEME_NAME} - generated by theme-set

return {{
    active_border   = {argb(active, "bb")},
    inactive_border = {argb(inactive, "aa")},
    shadow          = {argb(os.environ["base00"], "ee")},
}}
"""

path = os.path.join(CACHE_DIR, "hypr-colors.lua")
tmp = path + ".tmp"
with open(tmp, "w") as f:
    f.write(out)
os.replace(tmp, path)

# Hyprland watches its own config tree, but this file is pulled in with dofile
# from the cache dir, which the watcher never sees - so ask for the reload.
if shutil.which("hyprctl"):
    subprocess.run(["hyprctl", "reload"], stdout=subprocess.DEVNULL, check=False)
