# Hyprland border/decoration colors
# Receives: $base00-$base0F, $CACHE_DIR, $THEME_NAME

# Convert #RRGGBB + alpha to Lua numeric ARGB (0xAARRGGBB)
hex_to_lua_argb() {
    local hex="${1#\#}"
    local alpha="${2:-ff}"
    echo "0x${alpha}${hex}"
}

active_border="$(hex_to_lua_argb "$base0D" "bb")"
inactive_border="$(hex_to_lua_argb "$base03" "aa")"
shadow="$(hex_to_lua_argb "$base00" "ee")"

cat > "$CACHE_DIR/hypr-colors.lua.tmp" << EOF
-- Base16 theme: $THEME_NAME - generated by theme-set

return {
    active_border   = $active_border,
    inactive_border = $inactive_border,
    shadow          = $shadow,
}
EOF

# Atomic moves - Hyprland auto-reloads on file change
mv "$CACHE_DIR/hypr-colors.lua.tmp" "$CACHE_DIR/hypr-colors.lua"
