# Hyprland border/decoration colors
# Receives: $base00-$base0F, $CACHE_DIR, $THEME_NAME

# Convert hex to hyprland rgba format (RRGGBBAA)
hex_to_hypr() {
    local hex="${1#\#}"
    local alpha="${2:-ff}"
    echo "${hex}${alpha}"
}

cat > "$CACHE_DIR/hypr-colors.conf.tmp" << EOF
# Base16 theme: $THEME_NAME - generated by theme-set

\$theme_active_border = rgba($(hex_to_hypr "$base0D" "bb"))
\$theme_inactive_border = rgba($(hex_to_hypr "$base03" "aa"))
\$theme_shadow = rgba($(hex_to_hypr "$base00" "ee"))
EOF

# Atomic move - hyprland auto-reloads on file change
mv "$CACHE_DIR/hypr-colors.conf.tmp" "$CACHE_DIR/hypr-colors.conf"
