# Vencord/Vesktop theme generation
# Receives: $base00-$base0F, $THEME_NAME

VESKTOP_THEMES="$HOME/.config/vesktop/themes"

# Check for flatpak install if standard not found
[[ ! -d "$HOME/.config/vesktop" ]] && VESKTOP_THEMES="$HOME/.var/app/dev.vencord.Vesktop/config/vesktop/themes"

# Skip if vesktop not installed at all
[[ ! -d "$(dirname "$VESKTOP_THEMES")" ]] && return 0

mkdir -p "$VESKTOP_THEMES"

# Generate theme CSS using Python for color manipulation
python3 << EOF > "$VESKTOP_THEMES/base16.theme.css"
import colorsys

def hex_to_hls(hex_color):
    """Convert hex to HLS (colorsys uses HLS not HSL)"""
    hex_color = hex_color.lstrip('#')
    r, g, b = tuple(int(hex_color[i:i+2], 16) / 255 for i in (0, 2, 4))
    return colorsys.rgb_to_hls(r, g, b)

def hls_to_hex(h, l, s):
    """Convert HLS back to hex"""
    r, g, b = colorsys.hls_to_rgb(h, l, s)
    return '#{:02x}{:02x}{:02x}'.format(int(r*255), int(g*255), int(b*255))

def adjust_lightness(hex_color, amount):
    """Adjust lightness of a color by amount (-1 to 1)"""
    h, l, s = hex_to_hls(hex_color)
    l = max(0, min(1, l + amount))
    return hls_to_hex(h, l, s)

def shades(hex_color):
    """Generate 5 shades: lighter to darker"""
    return [
        adjust_lightness(hex_color, 0.10),   # shade-1: lighter
        hex_color,                            # shade-2: base
        adjust_lightness(hex_color, -0.05),  # shade-3
        adjust_lightness(hex_color, -0.10),  # shade-4
        adjust_lightness(hex_color, -0.15),  # shade-5: darker
    ]

# Base16 colors from environment
base00 = "$base00"  # background
base01 = "$base01"  # lighter bg
base02 = "$base02"  # selection
base03 = "$base03"  # comments
base04 = "$base04"  # dark fg
base05 = "$base05"  # foreground
base06 = "$base06"  # light fg
base07 = "$base07"  # lightest fg
base08 = "$base08"  # red
base09 = "$base09"  # orange
base0A = "$base0A"  # yellow
base0B = "$base0B"  # green
base0C = "$base0C"  # cyan
base0D = "$base0D"  # blue
base0E = "$base0E"  # purple
base0F = "$base0F"  # brown

# Generate color shades
red = shades(base08)
green = shades(base0B)
blue = shades(base0D)
yellow = shades(base0A)
purple = shades(base0E)
accent = shades(base0D)  # Use blue as accent

# Text shades - keep messages readable!
# base05 = main text, slightly dim for normal, base03 only for truly muted
text_1 = adjust_lightness(base05, 0.15)   # brightest (white-ish)
text_3 = adjust_lightness(base05, -0.08)  # normal text (slightly dimmed base05, NOT base04)
text_4 = adjust_lightness(base05, -0.20)  # icons/channels (more dimmed)
text_5 = adjust_lightness(base03, 0.0)    # muted/timestamps

# Background shades
bg_1 = adjust_lightness(base02, 0.08)

# Hover/active states (semi-transparent in HSL)
h, l, s = hex_to_hls(base03)

print(f'''/**
 * @name Base16 Theme: $THEME_NAME
 * @description Generated by theme-set from base16 colors
 * @author theme-set
 * @version 1.0.0
 */

/* Import midnight base theme */
@import url('https://refact0r.github.io/midnight-discord/build/midnight.css');

body {{
    /* Font settings */
    --font: 'figtree';
    --code-font: '';
    font-weight: 400;

    /* Layout */
    --gap: 12px;
    --divider-thickness: 4px;
    --border-thickness: 1px;

    /* Animations */
    --animations: on;
    --list-item-transition: 0.2s ease;
    --dms-icon-svg-transition: 0.4s ease;
    --border-hover-transition: 0.2s ease;

    /* Top bar */
    --top-bar-height: var(--gap);
    --top-bar-button-position: titlebar;
    --top-bar-title-position: off;
    --subtle-top-bar-title: off;

    /* Window controls */
    --custom-window-controls: on;
    --window-control-size: 14px;

    /* DMs button */
    --custom-dms-icon: hide;
    --custom-dms-background: off;

    /* Background */
    --background-image: off;

    /* Transparency */
    --transparency-tweaks: off;
    --remove-bg-layer: off;
    --panel-blur: off;
    --blur-amount: 12px;
    --bg-floating: var(--bg-3);

    /* Chatbar */
    --custom-chatbar: off;
    --chatbar-height: 47px;

    /* Other */
    --small-user-panel: on;
}}

:root {{
    --colors: on;

    /* Text colors */
    --text-0: var(--bg-3);
    --text-1: {text_1};
    --text-2: {text_3};
    --text-3: {base05};
    --text-4: {text_4};
    --text-5: {text_5};

    /* Background colors */
    --bg-1: {bg_1};
    --bg-2: {base02};
    --bg-3: {base01};
    --bg-4: {base00};
    --hover: hsla({int(h*360)}, {int(s*100)}%, {int(l*100)}%, 0.1);
    --active: hsla({int(h*360)}, {int(s*100)}%, {int(l*100)}%, 0.2);
    --active-2: hsla({int(h*360)}, {int(s*100)}%, {int(l*100)}%, 0.3);
    --message-hover: hsla(0, 0%, 0%, 0.1);

    /* Accent colors */
    --accent-1: {accent[0]};
    --accent-2: {accent[1]};
    --accent-3: {accent[2]};
    --accent-4: {accent[3]};
    --accent-5: {accent[4]};
    --accent-new: var(--red-2);
    --mention: linear-gradient(to right, color-mix(in hsl, var(--accent-2), transparent 90%) 40%, transparent);
    --mention-hover: linear-gradient(to right, color-mix(in hsl, var(--accent-2), transparent 95%) 40%, transparent);
    --reply: linear-gradient(to right, color-mix(in hsl, var(--text-3), transparent 90%) 40%, transparent);
    --reply-hover: linear-gradient(to right, color-mix(in hsl, var(--text-3), transparent 95%) 40%, transparent);

    /* Status colors */
    --online: var(--green-2);
    --dnd: var(--red-2);
    --idle: var(--yellow-2);
    --streaming: var(--purple-2);
    --offline: var(--text-4);

    /* Border colors */
    --border-light: var(--hover);
    --border: var(--active);
    --border-hover: var(--active);
    --button-border: hsla(0, 0%, 100%, 0.1);

    /* Red */
    --red-1: {red[0]};
    --red-2: {red[1]};
    --red-3: {red[2]};
    --red-4: {red[3]};
    --red-5: {red[4]};

    /* Green */
    --green-1: {green[0]};
    --green-2: {green[1]};
    --green-3: {green[2]};
    --green-4: {green[3]};
    --green-5: {green[4]};

    /* Blue */
    --blue-1: {blue[0]};
    --blue-2: {blue[1]};
    --blue-3: {blue[2]};
    --blue-4: {blue[3]};
    --blue-5: {blue[4]};

    /* Yellow */
    --yellow-1: {yellow[0]};
    --yellow-2: {yellow[1]};
    --yellow-3: {yellow[2]};
    --yellow-4: {yellow[3]};
    --yellow-5: {yellow[4]};

    /* Purple */
    --purple-1: {purple[0]};
    --purple-2: {purple[1]};
    --purple-3: {purple[2]};
    --purple-4: {purple[3]};
    --purple-5: {purple[4]};
}}
''')
EOF
