# Vicinae launcher theme generation
# Receives: $base00-$base0F, $CACHE_DIR, $THEME_NAME
#
# Roles follow bidshell's Config/Theme.qml so the launcher matches the popouts.
# settings.json points both appearances at this theme id, and vicinae
# hot-reloads the file, so there is nothing to call afterwards.

mode=$(jq -r '.mode' "$CACHE_DIR/state.json")
eval "$(jq -r --arg m "$mode" '.colors[$m] | to_entries[] | "md_\(.key)=\(.value | @sh)"' "$CACHE_DIR/dms-colors.json")"

dir="$HOME/.local/share/vicinae/themes"
mkdir -p "$dir"

cat > "$dir/theme-set.toml.tmp" << EOF
# $THEME_NAME - generated by theme-set

[meta]
name = "theme-set"
description = "$THEME_NAME ($mode)"
variant = "$mode"

[colors.core]
accent = "$md_primary"
accent_foreground = "$md_on_primary"
background = "$md_background"
foreground = "$md_on_surface"
secondary_background = "$md_surface_container"
border = "$md_outline_variant"

[colors.main_window]
border = { name = "$md_outline", opacity = 0.35 }

[colors.settings_window]
border = { name = "$md_outline", opacity = 0.35 }

# no material role carries a real red/green/yellow; error stays the red so
# danger text and the red accent agree
[colors.accents]
blue = "$base0D"
green = "$base0B"
magenta = "$base0E"
orange = "$base09"
red = "$md_error"
yellow = "$base0A"
cyan = "$base0C"
purple = "$base0F"

[colors.text]
default = "$md_on_surface"
muted = "$md_on_surface_variant"
danger = "$md_error"
success = "$base0B"
placeholder = { name = "$md_on_surface_variant", opacity = 0.6 }
selection = { background = "$md_primary", foreground = "$md_on_primary" }

[colors.text.links]
default = "$md_primary"
visited = "$base0E"

[colors.input]
border = "$md_outline_variant"
border_focus = "$md_primary"
border_error = "$md_error"

[colors.button.primary]
background = "$md_surface_container_high"
foreground = "$md_on_surface"
hover = { background = "$md_surface_container_highest" }
focus = { outline = "$md_primary" }

# hover is bidshell's state layer: on_surface at 8%
[colors.list.item.hover]
background = { name = "$md_on_surface", opacity = 0.08 }
foreground = "$md_on_surface"
secondary_foreground = "$md_on_surface_variant"

[colors.list.item.selection]
background = "$md_primary_container"
foreground = "$md_on_primary_container"
secondary_background = "$md_primary_container"
secondary_foreground = "$md_on_primary_container"

[colors.grid.item]
background = "$md_surface_container"
selection = { outline = "$md_primary" }

# vicinae drops the whole theme on an inline table nested in another one
[colors.grid.item.hover]
outline = { name = "$md_on_surface_variant", opacity = 0.5 }

[colors.scrollbars]
background = "$md_outline_variant"

[colors.loading]
bar = "$md_primary"
spinner = "$md_primary"
EOF
mv "$dir/theme-set.toml.tmp" "$dir/theme-set.toml"
