# Zen Browser theme generation
# Receives: $base00-$base0F, $THEME_NAME

# Find Zen profile chrome directory
ZEN_CHROME=$(find ~/.zen -maxdepth 2 -type d -name "chrome" 2>/dev/null | grep -v "storage" | head -1)
[[ -z "$ZEN_CHROME" ]] && return 0  # Zen not installed, skip

# Generate userChrome.css
cat > "$ZEN_CHROME/userChrome.css" << EOF
/* Base16 theme: $THEME_NAME - generated by theme-set */

@media (prefers-color-scheme: dark) {
  :root {
    --zen-colors-primary: $base02 !important;
    --zen-primary-color: $base0D !important;
    --zen-colors-secondary: $base02 !important;
    --zen-colors-tertiary: $base01 !important;
    --zen-colors-border: $base0D !important;
    --toolbarbutton-icon-fill: $base0D !important;
    --lwt-text-color: $base05 !important;
    --toolbar-field-color: $base05 !important;
    --tab-selected-textcolor: $base05 !important;
    --toolbar-field-focus-color: $base05 !important;
    --toolbar-color: $base05 !important;
    --newtab-text-primary-color: $base05 !important;
    --arrowpanel-color: $base05 !important;
    --arrowpanel-background: $base00 !important;
    --sidebar-text-color: $base05 !important;
    --lwt-sidebar-text-color: $base05 !important;
    --lwt-sidebar-background-color: $base01 !important;
    --toolbar-bgcolor: $base02 !important;
    --newtab-background-color: $base00 !important;
    --zen-themed-toolbar-bg: $base01 !important;
    --zen-main-browser-background: $base01 !important;
    --toolbox-bgcolor-inactive: $base01 !important;
  }

  #permissions-granted-icon {
    color: $base01 !important;
  }

  .sidebar-placesTree {
    background-color: $base00 !important;
  }

  #zen-workspaces-button {
    background-color: $base00 !important;
  }

  #TabsToolbar {
    background-color: $base01 !important;
  }

  .urlbar-background {
    background-color: $base00 !important;
  }

  .content-shortcuts {
    background-color: $base00 !important;
    border-color: $base0D !important;
  }

  .urlbarView-url {
    color: $base0D !important;
  }

  #zenEditBookmarkPanelFaviconContainer {
    background: $base01 !important;
  }

  #zen-media-controls-toolbar {
    & #zen-media-progress-bar {
      &::-moz-range-track {
        background: $base02 !important;
      }
    }
  }

  toolbar .toolbarbutton-1 {
    &:not([disabled]) {
      &:is([open], [checked])
        > :is(
          .toolbarbutton-icon,
          .toolbarbutton-text,
          .toolbarbutton-badge-stack
        ) {
        fill: $base01;
      }
    }
  }

  .identity-color-blue {
    --identity-tab-color: $base0D !important;
    --identity-icon-color: $base0D !important;
  }

  .identity-color-turquoise {
    --identity-tab-color: $base0C !important;
    --identity-icon-color: $base0C !important;
  }

  .identity-color-green {
    --identity-tab-color: $base0B !important;
    --identity-icon-color: $base0B !important;
  }

  .identity-color-yellow {
    --identity-tab-color: $base0A !important;
    --identity-icon-color: $base0A !important;
  }

  .identity-color-orange {
    --identity-tab-color: $base09 !important;
    --identity-icon-color: $base09 !important;
  }

  .identity-color-red {
    --identity-tab-color: $base08 !important;
    --identity-icon-color: $base08 !important;
  }

  .identity-color-pink {
    --identity-tab-color: $base0E !important;
    --identity-icon-color: $base0E !important;
  }

  .identity-color-purple {
    --identity-tab-color: $base0E !important;
    --identity-icon-color: $base0E !important;
  }

  hbox#titlebar {
    background-color: $base01 !important;
  }

  #zen-appcontent-navbar-container {
    background-color: $base01 !important;
  }
}
EOF

# Generate userContent.css
cat > "$ZEN_CHROME/userContent.css" << EOF
/* Base16 theme: $THEME_NAME - generated by theme-set */

@media (prefers-color-scheme: dark) {

  /* Common variables affecting all about: pages */
  @-moz-document url-prefix("about:") {
    :root {
      --in-content-page-color: $base05 !important;
      --color-accent-primary: $base0D !important;
      --color-accent-primary-hover: $base0D !important;
      --color-accent-primary-active: $base0D !important;
      background-color: $base00 !important;
      --in-content-page-background: $base00 !important;
    }
  }

  /* Variables and styles specific to about:newtab and about:home */
  @-moz-document url("about:newtab"), url("about:home") {
    :root {
      --newtab-background-color: $base00 !important;
      --newtab-background-color-secondary: $base02 !important;
      --newtab-element-hover-color: $base02 !important;
      --newtab-text-primary-color: $base05 !important;
      --newtab-wordmark-color: $base05 !important;
      --newtab-primary-action-background: $base0D !important;
    }

    .icon {
      color: $base0D !important;
    }

    .card-outer:is(:hover, :focus, .active):not(.placeholder) .card-title {
      color: $base0D !important;
    }

    .top-site-outer .search-topsite {
      background-color: $base0D !important;
    }

    .compact-cards .card-outer .card-context .card-context-icon.icon-download {
      fill: $base0B !important;
    }
  }

  /* Variables and styles specific to about:preferences */
  @-moz-document url-prefix("about:preferences") {
    :root {
      --zen-colors-tertiary: $base01 !important;
      --in-content-text-color: $base05 !important;
      --link-color: $base0D !important;
      --link-color-hover: $base0D !important;
      --zen-colors-primary: $base02 !important;
      --in-content-box-background: $base02 !important;
      --zen-primary-color: $base0D !important;
    }

    groupbox, moz-card {
      background: $base00 !important;
    }

    button,
    groupbox menulist {
      background: $base02 !important;
      color: $base05 !important;
    }

    .main-content {
      background-color: $base01 !important;
    }

    .identity-color-blue {
      --identity-tab-color: $base0D !important;
      --identity-icon-color: $base0D !important;
    }

    .identity-color-turquoise {
      --identity-tab-color: $base0C !important;
      --identity-icon-color: $base0C !important;
    }

    .identity-color-green {
      --identity-tab-color: $base0B !important;
      --identity-icon-color: $base0B !important;
    }

    .identity-color-yellow {
      --identity-tab-color: $base0A !important;
      --identity-icon-color: $base0A !important;
    }

    .identity-color-orange {
      --identity-tab-color: $base09 !important;
      --identity-icon-color: $base09 !important;
    }

    .identity-color-red {
      --identity-tab-color: $base08 !important;
      --identity-icon-color: $base08 !important;
    }

    .identity-color-pink {
      --identity-tab-color: $base0E !important;
      --identity-icon-color: $base0E !important;
    }

    .identity-color-purple {
      --identity-tab-color: $base0E !important;
      --identity-icon-color: $base0E !important;
    }
  }

  /* Variables and styles specific to about:addons */
  @-moz-document url-prefix("about:addons") {
    :root {
      --zen-dark-color-mix-base: $base01 !important;
      --background-color-box: $base00 !important;
    }
  }

  /* Variables and styles specific to about:protections */
  @-moz-document url-prefix("about:protections") {
    :root {
      --zen-primary-color: $base00 !important;
      --social-color: $base0E !important;
      --coockie-color: $base0C !important;
      --fingerprinter-color: $base0A !important;
      --cryptominer-color: $base0D !important;
      --tracker-color: $base0B !important;
      --in-content-primary-button-background-hover: $base02 !important;
      --in-content-primary-button-text-color-hover: $base05 !important;
      --in-content-primary-button-background: $base02 !important;
      --in-content-primary-button-text-color: $base05 !important;
    }

    .card {
      background-color: $base02 !important;
    }
  }
}
EOF
