[project]
name = "mouseless"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "evdev>=1.9.2",
    "pygobject>=3.52.3",
    "pyqt6>=6.9.0",
    "qasync>=0.27.1",
]

[tool.pyright]
typeCheckingMode = "standard"
