pragma Singleton

import QtQuick
import Quickshell

// Lucide glyphs by icon name, for Theme.fontIcons. Codepoints come from
// assets/fonts/lucide/codepoints.json and are only valid for the bundled font; the ones
// past the BMP are icons assets/fonts/lucide/extra/add-icons.py adds to it.
Singleton {
    readonly property string power: "\ue140"
    readonly property string lock: "\ue10b"
    readonly property string moon: "\ue11e"
    readonly property string logOut: "\ue10e"
    readonly property string rotateCcw: "\ue148"
    readonly property string bell: "\ue059"
    readonly property string mic: "\ue118"
    readonly property string micOff: "\ue119"
    readonly property string volume: "\ue1a9"
    readonly property string volume1: "\ue1aa"
    readonly property string volume2: "\ue1ab"
    readonly property string volumeX: "\ue1ac"
    readonly property string batteryLow: "\ue056"
    readonly property string batteryMedium: "\ue057"
    readonly property string batteryFull: "\ue055"
    readonly property string batteryCharging: "\ue054"
    readonly property string batteryWarning: "\ue3ac"
    readonly property string leaf: "\ue2de"
    readonly property string scale: "\ue212"
    readonly property string rocket: "\ue286"
    readonly property string thermometer: "\ue186"
    readonly property string info: "\ue0f9"
    readonly property string mouse: "\ue28e"
    readonly property string keyboard: "\ue284"
    readonly property string headphones: "\ue0f1"
    readonly property string touchpad: "\ue449"
    readonly property string gamepad2: "\ue0df"
    readonly property string smartphone: "\ue163"
    readonly property string speaker: "\ue166"
    readonly property string shieldCheck: "\ue1ff"
    readonly property string loaderCircle: "\ue10a"
    readonly property string audioLines: "\ue55a"
    readonly property string skipBack: "\ue15f"
    readonly property string skipForward: "\ue160"
    readonly property string play: "\ue13c"
    readonly property string pause: "\ue12e"
    readonly property string circleStop: "\ue083"
    readonly property string chevronDown: "\ue06d"
    readonly property string chevronUp: "\ue070"
    readonly property string chevronLeft: "\ue06e"
    readonly property string chevronRight: "\ue06f"
    readonly property string sun: "\ue178"
    readonly property string cloud: "\ue088"
    readonly property string cloudSun: "\ue216"
    readonly property string cloudMoon: "\ue215"
    readonly property string cloudRain: "\ue08e"
    readonly property string cloudDrizzle: "\ue08a"
    readonly property string cloudSnow: "\ue090"
    readonly property string cloudLightning: "\ue08c"
    readonly property string cloudFog: "\ue214"
    readonly property string wind: "\ue1b0"
    readonly property string appWindow: "\ue426"
    readonly property string square: "\ue167"
    readonly property string squareCheck: "\ue559"
    readonly property string circle: "\ue076"
    readonly property string circleDot: "\ue345"
    readonly property string wifi: "\ue1ae"
    readonly property string wifiZero: "\ue5f9"
    readonly property string wifiLow: "\ue5f8"
    readonly property string wifiHigh: "\ue5f7"
    readonly property string wifiOff: "\ue1af"
    readonly property string bluetooth: "\ue05c"
    readonly property string bluetoothOff: "\ue1b9"
    readonly property string laptop: "\ue1cd"
    readonly property string headset: "\ue5bd"
    readonly property string plane: "\ue1de"
    readonly property string music: "\ue122"
    readonly property string droplets: "\ue0b5"
    readonly property string umbrella: "\ue199"
    readonly property string camera: "\ue064"
    readonly property string video: "\ue1a5"
    readonly property string monitor: "\ue11d"
    readonly property string crop: "\ue0ab"
    readonly property string scanSearch: "\ue537"
    readonly property string scanText: "\ue538"
    readonly property string languages: "\ue0fe"
    readonly property string x: "\ue1b2"
    readonly property string copy: "\ue09e"
    readonly property string pencil: "\ue1f9"
    readonly property string save: "\ue14d"
    readonly property string monitorSmartphone: "\ue3a2"
    readonly property string coffee: "\ue096"
    readonly property string pipette: "\ue13b"
    readonly property string check: "\ue06c"
    readonly property string search: "\ue151"
    readonly property string refreshCw: "\ue145"
    readonly property string slidersHorizontal: "\ue29a"
    readonly property string arrowRight: "\ue049"
    readonly property string listX: "\ue240"
    readonly property string zap: "\ue1b4"
    readonly property string link: "\ue102"
    readonly property string unlink: "\ue19c"
    readonly property string ethernetPort: "\ue620"
    readonly property string bellOff: "\ue05a"
    readonly property string asterisk: "\ue1ef"
    readonly property string shieldLock: "\ue731"
    // U+F0000, from Tabler
    readonly property string hdr: "\udb80\udc00"
    readonly property string mapPin: "\ue111"
}
