pragma Singleton

import QtQuick
import Quickshell

// Lucide glyphs by icon name, for Theme.fontIcons. Codepoints come from
// assets/fonts/lucide/codepoints.json and are only valid for the bundled font.
Singleton {
    readonly property string power: "\ue140"
    readonly property string lock: "\ue10b"
    readonly property string moon: "\ue11e"
    readonly property string logOut: "\ue10e"
    readonly property string rotateCcw: "\ue148"
    readonly property string bell: "\ue059"
    readonly property string bellDot: "\ue42b"
    readonly property string mic: "\ue118"
    readonly property string micOff: "\ue119"
    readonly property string volume: "\ue1a9"
    readonly property string volume1: "\ue1aa"
    readonly property string volume2: "\ue1ab"
    readonly property string volumeX: "\ue1ac"
    readonly property string battery: "\ue053"
    readonly property string batteryLow: "\ue056"
    readonly property string batteryMedium: "\ue057"
    readonly property string batteryFull: "\ue055"
    readonly property string batteryCharging: "\ue054"
    readonly property string batteryWarning: "\ue3ac"
    readonly property string mouse: "\ue28e"
    readonly property string keyboard: "\ue284"
    readonly property string headphones: "\ue0f1"
    readonly property string touchpad: "\ue449"
    readonly property string gamepad2: "\ue0df"
    readonly property string smartphone: "\ue163"
    readonly property string speaker: "\ue166"
    readonly property string shieldCheck: "\ue1ff"
    readonly property string loaderCircle: "\ue10a"
    readonly property string audioLines: "\ue55a"
    readonly property string skipBack: "\ue15f"
    readonly property string skipForward: "\ue160"
    readonly property string play: "\ue13c"
    readonly property string pause: "\ue12e"
    readonly property string circleStop: "\ue083"
    readonly property string chevronDown: "\ue06d"
    readonly property string chevronUp: "\ue070"
    readonly property string chevronLeft: "\ue06e"
    readonly property string chevronRight: "\ue06f"
    readonly property string sun: "\ue178"
    readonly property string cloud: "\ue088"
    readonly property string cloudSun: "\ue216"
    readonly property string cloudMoon: "\ue215"
    readonly property string cloudRain: "\ue08e"
    readonly property string cloudDrizzle: "\ue08a"
    readonly property string cloudSnow: "\ue090"
    readonly property string cloudLightning: "\ue08c"
    readonly property string cloudFog: "\ue214"
    readonly property string cloudHail: "\ue08b"
    readonly property string snowflake: "\ue165"
    readonly property string wind: "\ue1b0"
    readonly property string appWindow: "\ue426"
    readonly property string square: "\ue167"
    readonly property string squareCheck: "\ue559"
    readonly property string circle: "\ue076"
    readonly property string circleDot: "\ue345"
}
