# hyprlang if !notebook

monitorv2 {
    output        = $mainMonitor
    mode          = highres highrr
    position      = 0x0
    scale         = 1.0
    bitdepth      = 10
    sdrbrightness = 1.2
    sdrsaturation = 1.2
    cm            = srgb
}

monitorv2 {
    output       = $miniMonitor
    mode         = preferred
    scale        = 1.2
    position     = auto-center-down
    supports_hdr = -1
}


# hyprlang endif

# hyprlang if notebook

monitorv2 {
    output   = eDP-1
    mode     = 2880x1800@60.0
    position = 0x0
    scale    = 1.5
    bitdepth = 10
    vrr      = 1
    cm       = srgb
}

# hyprlang endif
